### ISSUE TITLE
FileNotFoundError: Couldn't find any class folder in ./datasets/cifar100/base.

### ISSUE THREAD

**Issue by ChibisukeDragon** [BruceQFWang/learngene#1]
I wan to make continual data (source domain) and target data(target domain) on the CIFAR100 dataset. Here is my command:

first:
```
(learngene) yupeng@ubuntu:~/learngene/learngene$
(learngene) yupeng@ubuntu:~/learngene/learngene$ python utils/data_cifar_mk.py --num_imgs_per_cat_train 600 --path ./datasets/cifar100
Traceback (most recent call last):
  File "/home/yupeng/learngene/learngene/utils/data_cifar_mk.py", line 367, in <module>
    train_ll_loader, train_mm_loader, test_loader = get_cifar100_dataloaders(num_tasks, \
  File "/home/yupeng/learngene/learngene/utils/data_cifar_mk.py", line 331, in get_cifar100_dataloaders
    dataset_train = GenericDataset_ll(dir_name, 'cifar100','base', task_iter_item = i, subtask_class_num=subtask_classes_num, \
  File "/home/yupeng/learngene/learngene/utils/data_cifar_mk.py", line 108, in __init__
    self.data = datasets.ImageFolder(split_data_dir, self.transform)
  File "/home/yupeng/anaconda3/envs/learngene/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 310, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "/home/yupeng/anaconda3/envs/learngene/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/yupeng/anaconda3/envs/learngene/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 221, in find_classes
    return find_classes(directory)
  File "/home/yupeng/anaconda3/envs/learngene/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
FileNotFoundError: [Errno 2] No such file or directory: './datasets/cifar100/base'
(learngene) yupeng@ubuntu:~/learngene/learngene$
```

second (after I created a folder named base in ./datasets/cifar100/):
```
(learngene) yupeng@ubuntu:~/learngene/learngene$
(learngene) yupeng@ubuntu:~/learngene/learngene$ python utils/data_cifar_mk.py --num_imgs_per_cat_train 600 --path ./datasets/cifar100
./datasets/cifar100/base
Traceback (most recent call last):
  File "/home/yupeng/learngene/learngene/utils/data_cifar_mk.py", line 368, in <module>
    train_ll_loader, train_mm_loader, test_loader = get_cifar100_dataloaders(num_tasks, \
  File "/home/yupeng/learngene/learngene/utils/data_cifar_mk.py", line 332, in get_cifar100_dataloaders
    dataset_train = GenericDataset_ll(dir_name, 'cifar100','base', task_iter_item = i, subtask_class_num=subtask_classes_num, \
  File "/home/yupeng/learngene/learngene/utils/data_cifar_mk.py", line 109, in __init__
    self.data = datasets.ImageFolder(split_data_dir, self.transform)
  File "/home/yupeng/anaconda3/envs/learngene/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 310, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "/home/yupeng/anaconda3/envs/learngene/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/yupeng/anaconda3/envs/learngene/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 221, in find_classes
    return find_classes(directory)
  File "/home/yupeng/anaconda3/envs/learngene/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in ./datasets/cifar100/base.
(learngene) yupeng@ubuntu:~/learngene/learngene$
```

The directory structure of the files is as follows:
```
/home/yupeng/learngene/learngene/
├── collective-model/
├── datasets/
│     └── cifar-100/
│         ├── meta
│         ├── test
│         └── train
├── utils/
└── other codes
```
How to create files structure for cifar100?

您好，我想请问关于cifar100的目录结构应该是怎样的，代码似乎在寻找base文件夹下的类数据？

**Comment by BruceQiufengWang** [comment]
base文件就对应着cifar-100/train文件，里面总共64个类，具体如何划分cifar100数据集，也可以参考我们的补充材料:https://github.com/BruceQFWang/learngene/blob/main/Learngene_Appendix.pdf

**Comment by ChibisukeDragon** [comment]
@BruceQFWang 谢谢！
所以我应该事先手动将cifar-100/train读取出来，应该是一个dictionary。将其按您补充材料中对cifar100的base、novel、openworld划分好后，再存储为cifar-100/base、cifar-100/novel、cifar-100/openworld，之后再使用python data_cifar_mk.py是吗？
我原本以为utils/data_cifar_mk.py是做拆分这件事的，但是好像不是这样。。。

**Comment by ChibisukeDragon** [comment]
我刚试了一下，只把cifar-100/train重命名为cifar-100/base好像还是不行，和上面first的报错相同。
所以还是想请教下您，具体的数据集放置方法。
![QQ截图20220305224749](https://user-images.githubusercontent.com/32593426/156888406-d3b6acc8-8049-49cf-8c23-e10bf7b84709.png)

**Comment by BruceQiufengWang** [comment]
是的，需要首先按照补充材料把cifar100划分成base、novel、openworld三个文件夹，然后再运行python data_cifar_mk.py 。我上传了cifar100划分好的文件，点击下载：https://drive.google.com/file/d/1MKWi7dsjp3RQkKrcLV7ljZxJ4sm3YTL5/view?usp=sharing

**Comment by BruceQiufengWang** [comment]
刚刚的链接好像受限了，更新下下载链接：https://drive.google.com/file/d/1MKWi7dsjp3RQkKrcLV7ljZxJ4sm3YTL5/view?usp=sharing

**Comment by ChibisukeDragon** [comment]
@BruceQFWang 
谢谢！！！
我下载了数据，放进去后，能输出正确的内容。
但是该程序在最后即将要返回时，返回值之一“dataloader_train_mm”是未定义的内容。麻烦您再指点一下。
```
(learngene) yupeng@ubuntu:~/learngene/learngene$ python utils/data_cifar_mk.py --num_imgs_per_cat_train 600 --path ./datasets/cifar100-open
lifelong data Task 0 done! 
lifelong data Task 1 done! 
......
lifelong data Task 49 done! 
inheritable data Task 0 done! 
inheritable data Task 1 done! 
......
inheritable data Task 49 done!
Traceback (most recent call last):
  File "/home/yupeng/learngene/learngene/utils/data_cifar_mk.py", line 367, in <module>
    train_ll_loader, train_mm_loader, test_loader = get_cifar100_dataloaders(num_tasks, \
  File "/home/yupeng/learngene/learngene/utils/data_cifar_mk.py", line 350, in get_cifar100_dataloaders
    return dataset_train, dataloader_train_mm, dataloader_test
NameError: name 'dataloader_train_mm' is not defined
(learngene) yupeng@ubuntu:~/learngene/learngene$
```

**Comment by BruceQiufengWang** [comment]
整理代码的时候忘记删了，这个return的内容其实不影响结果，只要生成了lifelong/inheritable data Task就行。

**Comment by ChibisukeDragon** [comment]
十分感谢~！！！
Thank you very much!!!
